import Navbar from "@/components/navbar/core/MainNav";
import TopNav from "@/components/navbar/core/TopNav";
import Footer from "@/components/footer/Footer";
import { Exo, Exo_2 } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import HomeFeatureCard from "@/components/featureCard/FeatureCard";

const exoSans = Exo({
  variable: "--font-exo-sans",
  subsets: ["latin"],
});

const exo_2 = Exo_2({
  variable: "--font-exo_2-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${exoSans.className} ${exo_2.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">

        {/* First Nav */}
        <TopNav />

        {/* Top navigation bar */}
        <Navbar />

        {/* Main page content (dynamic per route) */}

        {children}

        {/* Bottom footer */}

        <HomeFeatureCard />

        <Footer />
      </body>
    </html>
  );
}
